package com.piyush.app.blockchain.main;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import com.piyush.app.blockchain.Block;
import com.piyush.app.blockchain.BlockChain;
import com.piyush.app.blockchain.Data;
import com.piyush.app.blockchain.utils.Utils;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {

	@SuppressWarnings("unchecked")
	public static void main(String[] args) {
		ArrayList<Block> list=new ArrayList<Block>();
		BlockChain bc = new BlockChain();
		try {
			list.add(bc.generateBlock(new Block(new Data("piyush1",28)),list));
			list.add(bc.generateBlock(new Block(new Data("piyush2",28)),list));
			list.add(bc.generateBlock(new Block(new Data("piyush3",28)),list));
			
			//list.add(1, bc.generateBlock(new Block(new Data("piyush2",29)),list));
			
			Map<String,Object> m=Utils.isBlockChainValid(list);
			if(!m.isEmpty()) {
				Block b=(Block) m.get("block");
				System.out.println("Block Chain is altered at index"+m.get("index")+"\n \n \n");
			}
			
			for(Block block:list)
			{
				System.out.println(block.toString());
			}
		}
		catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

}
